apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: city-booking-ingress
  namespace: city-booking
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
spec:
  ingressClassName: nginx
  rules:
    - host: booking.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: city-booking-server
                port:
                  number: 18100
          - path: /
            pathType: Prefix
            backend:
              service:
                name: city-booking-web
                port:
                  number: 80
